chore: shfmt All The Things

diff --git a/fzmake/fzmake b/fzmake/fzmake
--- a/fzmake/fzmake
+++ b/fzmake/fzmake
@@ -2,76 +2,76 @@
 set -Eeuo pipefail
 
 panic() {
-    echo "${*}" >&2
-    exit 1
+  echo "${*}" >&2
+  exit 1
 }
 
 find_makefile() {
-    # find a Makefile in the current directory.
-    #
-    # will write file path of the first Makefile found to stdout
-    # if no makefile found, will panic
+  # find a Makefile in the current directory.
+  #
+  # will write file path of the first Makefile found to stdout
+  # if no makefile found, will panic
 
-    # https://www.gnu.org/software/make/manual/html_node/Makefile-Names.html
-    # order matters
-    makefile_names=(
-        GNUmakefile
-        makefile
-        Makefile
-    )
+  # https://www.gnu.org/software/make/manual/html_node/Makefile-Names.html
+  # order matters
+  makefile_names=(
+    GNUmakefile
+    makefile
+    Makefile
+  )
 
-    for f in "${makefile_names[@]}"; do
-        if [ -f "${f}" ]; then
-            echo "${f}"
-            return 0
-        fi
-    done
-    panic "No Makefile found in this directory."
+  for f in "${makefile_names[@]}"; do
+    if [ -f "${f}" ]; then
+      echo "${f}"
+      return 0
+    fi
+  done
+  panic "No Makefile found in this directory."
 }
 
 get_target_list() {
-    local makefile_path
-    makefile_path="$(printf %q "${1}")"
-    # return list of makefile targets in `##:target_name` format, where ## is the line number
-    # shellcheck disable=SC2086  # makefile_path has been escaped, no need to quote
-    grep --line-number \
-        --color=never \
-        --ignore-case \
-        --perl-regexp '^\S+:' \
-        --only-matching \
-        ${makefile_path} \
-        | awk -F ':' '$2 != ".PHONY" { print $1 ":" $2 }'
+  local makefile_path
+  makefile_path="$(printf %q "${1}")"
+  # return list of makefile targets in `##:target_name` format, where ## is the line number
+  # shellcheck disable=SC2086  # makefile_path has been escaped, no need to quote
+  grep --line-number \
+    --color=never \
+    --ignore-case \
+    --perl-regexp '^\S+:' \
+    --only-matching \
+    ${makefile_path} \
+    | awk -F ':' '$2 != ".PHONY" { print $1 ":" $2 }'
 }
 
 exec_fzf() {
-    SHELL="sh" fzf "${@}"
+  SHELL="sh" fzf "${@}"
 }
 
 main() {
-    local initial_query="${*:-}"
+  local initial_query="${*:-}"
 
-    export FZMAKE_MAKEFILE_PATH="${FZMAKE_MAKEFILE_PATH:-"$(find_makefile)"}"
-    local makefile_dir
-    makefile_dir="$(dirname "${FZMAKE_MAKEFILE_PATH}")"
+  export FZMAKE_MAKEFILE_PATH="${FZMAKE_MAKEFILE_PATH:-"$(find_makefile)"}"
+  local makefile_dir
+  makefile_dir="$(dirname "${FZMAKE_MAKEFILE_PATH}")"
 
-    local targets_to_run
-    readarray -t targets_to_run < <(
-        get_target_list "${FZMAKE_MAKEFILE_PATH}" \
-        | exec_fzf --ansi \
-            --query "${initial_query}" \
-            --delimiter : \
-            --with-nth 2 \
-            --preview "bat --color=always --highlight-line {1} --terminal-width \${FZF_PREVIEW_COLUMNS} --wrap never \"\${FZMAKE_MAKEFILE_PATH}\"" \
-            --preview-window 'up,70%,border-bottom,+{1}+3/3,~3' \
-            --multi \
-        | awk -F ':' '{print $2}' \
-    )
+  local targets_to_run
+  readarray -t targets_to_run < <(
+    get_target_list "${FZMAKE_MAKEFILE_PATH}" \
+      | exec_fzf --ansi \
+        --query "${initial_query}" \
+        --delimiter : \
+        --with-nth 2 \
+        --preview "bat --color=always --highlight-line {1} --terminal-width \${FZF_PREVIEW_COLUMNS} --wrap never \"\${FZMAKE_MAKEFILE_PATH}\"" \
+        --preview-window 'up,70%,border-bottom,+{1}+3/3,~3' \
+        --multi \
+      | awk -F ':' '{print $2}'
+  )
 
-    if [ "${#targets_to_run[@]}" -eq 0 ]; then
-        echo "No target selected. Aborting."
-    else
-        make --directory "${makefile_dir}" --file "${FZMAKE_MAKEFILE_PATH}" "${targets_to_run[@]}"
-    fi
+  if [ "${#targets_to_run[@]}" -eq 0 ]; then
+    echo "No target selected. Aborting."
+  else
+    make --directory "${makefile_dir}" --file "${FZMAKE_MAKEFILE_PATH}" "${targets_to_run[@]}"
+  fi
 }
 
 main "${@}"
diff --git a/fzpu/fzpu b/fzpu/fzpu
--- a/fzpu/fzpu
+++ b/fzpu/fzpu
@@ -19,16 +19,17 @@ CLI_ARGS=("${@}")
 
 select_job_ids() {
 
-    local js_query
+  local js_query
 
-    # construct an `fx` query that returns the following lines from `pueue status --json`:
-    #
-    #     TASK_ID\\STATUS\\COMMAND\\PATH\\GROUP
-    #
-    # we will use `\\` as the delimiter later when running the `column` command, to give
-    # us a nice table output.
-    #
-    js_query="$(cat <<EOF
+  # construct an `fx` query that returns the following lines from `pueue status --json`:
+  #
+  #     TASK_ID\\STATUS\\COMMAND\\PATH\\GROUP
+  #
+  # we will use `\\` as the delimiter later when running the `column` command, to give
+  # us a nice table output.
+  #
+  js_query="$(
+    cat <<EOF
 status => Object.values(status.tasks)
     .map(task => {
         // task.status can be one of the following:
@@ -47,42 +48,42 @@ status => Object.values(status.tasks)
     })
     .join("\n")
 EOF
-)"
+  )"
 
-    # shellcheck disable=SC1003  # double-backslash is not meant for escaping.
-    pueue status --json \
-        | fx "${js_query}" \
-        | column \
-            --table \
-            --separator '\' \
-            --table-columns ID,Status,Command,Path,Group \
-            --table-truncate Command,Path \
-            --table-noextreme Command,Path \
-            --output-width "${OUTPUT_WIDTH}" \
-        | fzf --multi --tac --height 10 --header-lines 1 \
-        | awk '{print $1}'
+  # shellcheck disable=SC1003  # double-backslash is not meant for escaping.
+  pueue status --json \
+    | fx "${js_query}" \
+    | column \
+      --table \
+      --separator '\' \
+      --table-columns ID,Status,Command,Path,Group \
+      --table-truncate Command,Path \
+      --table-noextreme Command,Path \
+      --output-width "${OUTPUT_WIDTH}" \
+    | fzf --multi --tac --height 10 --header-lines 1 \
+    | awk '{print $1}'
 }
 
 main() {
-    if [ "${#CLI_ARGS[@]}" -eq 0 ]; then
-        # user just wants to see `pueue status`
-        pueue status
-        exit 0
-    fi
+  if [ "${#CLI_ARGS[@]}" -eq 0 ]; then
+    # user just wants to see `pueue status`
+    pueue status
+    exit 0
+  fi
 
-    OUTPUT_WIDTH="$(tput cols)"
-    OUTPUT_WIDTH=$((OUTPUT_WIDTH-3))
+  OUTPUT_WIDTH="$(tput cols)"
+  OUTPUT_WIDTH=$((OUTPUT_WIDTH - 3))
 
-    if [ "${OUTPUT_WIDTH}" -le 0 ]; then
-        echo "Error: output width \"${OUTPUT_WIDTH}\"?"
-        exit 1
-    fi
+  if [ "${OUTPUT_WIDTH}" -le 0 ]; then
+    echo "Error: output width \"${OUTPUT_WIDTH}\"?"
+    exit 1
+  fi
 
-    local jobs
-    jobs="$(select_job_ids)"
-    test "${jobs}" != "" || exit 1  # user probably hit ctrl+c in fzf interface
+  local jobs
+  jobs="$(select_job_ids)"
+  test "${jobs}" != "" || exit 1 # user probably hit ctrl+c in fzf interface
 
-    echo "${jobs}" | xargs pueue "${CLI_ARGS[@]}"
+  echo "${jobs}" | xargs pueue "${CLI_ARGS[@]}"
 }
 
 main
